# Generated by Django 3.0.2 on 2020-02-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20200223_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
